language: java
services:
  - docker
  - mongodb
addons:
  sonarcloud:
    organization: "org-uzh-ase"
    token:
      secure: $SONAR_TOKEN  # encrypted value of your token
script:
  - mvn clean verify sonar:sonar -Pcoverage

  # Docker buil check
  # - docker build -t quiz .
  # - docker run -d -p 8080:8080 quiz
  # - docker ps -a